name: Sync Ofgem State & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: sync-state-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync-and-deploy:
    # Single run per push; we don't amend or create extra commits to avoid extra deployments
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Sync latest state (no emails)
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          NOTIFY_EMAILS: ${{ secrets.NOTIFY_EMAILS }}
        run: |
          set -euxo pipefail
          node ofgem-poll.js --sync-state

      # Deploy the synced working tree directly to Railway (no extra commit → single deployment)
      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service ${{ secrets.RAILWAY_SERVICE_ID }}
