name: Sync Ofgem State

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  sync-state:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Sync latest state (no emails)
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          NOTIFY_EMAILS: ${{ secrets.NOTIFY_EMAILS }}
        run: |
          node ofgem-poll.js --sync-state

      - name: Commit state if changed
        run: |
          if ! git diff --quiet -- last_ofgem_publication.json; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add last_ofgem_publication.json
            git commit -m "[sync-state] Update latest publication [skip ci]"
            git push
          else
            echo "No state change; skipping commit."
          fi


